export interface Product {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  price: number;
  oldPrice?: number;
  weight?: string;
  rating: number;
  reviews: number;
  badge?: string;
  inStock: boolean;
  image: string;
  gallery?: string[];
  description?: string;
}

// Product photos — Unsplash (reliable, no hotlink protection)
const U = 'https://images.unsplash.com/photo-';
const VIAL = [
  U + '1584308666744-24d5c474f2ae?w=500&q=90&fit=crop',
  U + '1559757175-0eb30cd8c063?w=500&q=90&fit=crop',
  U + '1631549916768-4119b2e5f926?w=500&q=90&fit=crop',
  U + '1617972436741-4b46ec6e4a53?w=500&q=90&fit=crop',
  U + '1576091160550-2173dba999ef?w=500&q=90&fit=crop',
];
const IMG = {
  // Protein tubs & powder
  on_whey_choc:      '/products/on-whey.png',
  on_whey_vanilla:   '/products/on-whey.png',
  on_whey_straw:     '/products/on-whey.png',
  on_isolate:        U + '1579722821273-0f6c1d44362b?w=500&q=90&fit=crop',
  on_casein:         U + '1512069772995-ec65ed45afd6?w=500&q=90&fit=crop',
  on_creatine:       U + '1617972436741-4b46ec6e4a53?w=500&q=90&fit=crop',
  on_preworkout:     U + '1546483875-ad9014c88eba?w=500&q=90&fit=crop',
  on_amino:          U + '1627467959547-2af8f75b6003?w=500&q=90&fit=crop',
  // BSN
  bsn_syntha:        U + '1563289591-0a3b54fbef24?w=500&q=90&fit=crop',
  bsn_noxplode:      U + '1571019613454-1cb2f99b2d8b?w=500&q=90&fit=crop',
  bsn_aminox:        U + '1534438327276-14e5300c3a48?w=500&q=90&fit=crop',
  bsn_truemass:      U + '1593095948071-474c5cc2989d?w=500&q=90&fit=crop',
  bsn_bar:           U + '1490645935967-10de6ba17061?w=500&q=90&fit=crop',
  // Now Foods vitamins
  now_d3:            U + '1584308666744-24d5c474f2ae?w=500&q=90&fit=crop',
  now_omega3:        U + '1550572017-edd951b55104?w=500&q=90&fit=crop',
  now_magnesium:     U + '1631549916768-4119b2e5f926?w=500&q=90&fit=crop',
  now_vitc:          U + '1584308666744-24d5c474f2ae?w=500&q=90&fit=crop',
  now_caps:          U + '1559757175-0eb30cd8c063?w=500&q=90&fit=crop',
  now_carnitine:     U + '1560343819-a63a5c04a4a5?w=500&q=90&fit=crop',
  now_kre:           U + '1617972436741-4b46ec6e4a53?w=500&q=90&fit=crop',
  // Balkan
  balkan_creatine:   U + '1517836357463-d25dfeac3438?w=500&q=90&fit=crop',
  balkan_whey:       U + '1556909114-f6e7ad7d3136?w=500&q=90&fit=crop',
  balkan_preworkout: U + '1546483875-ad9014c88eba?w=500&q=90&fit=crop',
  balkan_carnitine:  U + '1559757175-0eb30cd8c063?w=500&q=90&fit=crop',
  // Enervit
  enervit_drink:     U + '1550572017-edd951b55104?w=500&q=90&fit=crop',
  enervit_gel:       U + '1627467959547-2af8f75b6003?w=500&q=90&fit=crop',
  enervit_bar:       U + '1506459954879-8db95d17ebc0?w=500&q=90&fit=crop',
};

export const PRODUCTS: Product[] = [

  // ─── WHEY PROTEIN ─────────────────────────────────────────────────────────
  { id: 'p01', slug: 'on-whey-vanilla-2270g',        name: 'Gold Standard 100% Whey — Vanilla Ice Cream 2.27kg',       brand: 'Optimum Nutrition',    category: 'Protein',      subcategory: 'Whey Protein',         price: 64.99, oldPrice: 74.99, weight: '2.27 kg',      rating: 4.9, reviews: 512, badge: 'BESTSELLER', inStock: true,  image: '/products/on-whey-vanilla-main.png', gallery: ['/products/on-whey-vanilla-main.png', '/products/on-whey-vanilla-2.png', '/products/on-whey-vanilla-3.png', '/products/on-whey-vanilla-4.png', '/products/on-whey-vanilla-5.png'] },
  { id: 'p02', slug: 'on-whey-chocolate-2270g',      name: 'Gold Standard 100% Whey — Double Rich Chocolate 2.27kg',   brand: 'Optimum Nutrition',    category: 'Protein',      subcategory: 'Whey Protein',         price: 64.99, oldPrice: 74.99, weight: '2.27 kg',      rating: 4.9, reviews: 634, badge: 'BESTSELLER', inStock: true,  image: IMG.on_whey_choc,    gallery: ['/products/on-whey.png', '/products/on-whey-choc-1.png', '/products/on-whey-choc-2.png', '/products/on-whey-choc-3.png', '/products/on-whey-choc-4.png'] },
  { id: 'p03', slug: 'on-whey-strawberry-900g',      name: 'Gold Standard 100% Whey — Strawberry Banana 900g',         brand: 'Optimum Nutrition',    category: 'Protein',      subcategory: 'Whey Protein',         price: 34.99,               weight: '900 g',           rating: 4.8, reviews: 198,                       inStock: true,  image: '/products/on-whey-straw-main.png', gallery: ['/products/on-whey-straw-main.png', '/products/on-whey-straw-2.png', '/products/on-whey-straw-3.png', '/products/on-whey-straw-4.png'] },
  { id: 'p04', slug: 'bsn-syntha6-chocolate-2270g',  name: 'SYNTHA-6 Protein Matrix — Chocolate Milkshake 2.27kg',     brand: 'BSN',                  category: 'Protein',      subcategory: 'Whey Protein',         price: 52.99, oldPrice: 59.99, weight: '2.27 kg',      rating: 4.7, reviews: 287, badge: '-14%',        inStock: true,  image: '/products/bsn-syntha6-main.png', gallery: ['/products/bsn-syntha6-main.png', '/products/bsn-syntha6-2.png', '/products/bsn-syntha6-3.png', '/products/bsn-syntha6-4.png', '/products/bsn-syntha6-5.png'] },
  { id: 'p05', slug: 'balkan-whey-vanilla-900g',     name: 'Whey Protein Pro — Vanilla 900g',                          brand: 'Balkan Pharmaceuticals',category: 'Protein',     subcategory: 'Whey Protein',         price: 26.99,               weight: '900 g',           rating: 4.6, reviews: 143,                       inStock: true,  image: '/products/balkan-whey-vanilla-main.png', gallery: ['/products/balkan-whey-vanilla-main.png'] },

  // ─── PROTEIN ISOLATE ──────────────────────────────────────────────────────
  { id: 'p06', slug: 'on-isolate-vanilla-726g',      name: 'Gold Standard 100% Isolate — Vanilla Bean 726g',           brand: 'Optimum Nutrition',    category: 'Protein',      subcategory: 'Protein Isolate',      price: 54.99, oldPrice: 62.99, weight: '726 g',        rating: 4.9, reviews: 312, badge: '-12%',        inStock: true,  image: '/products/on-isolate-vanilla-main.png', gallery: ['/products/on-isolate-vanilla-main.png', '/products/on-isolate-vanilla-2.png', '/products/on-isolate-vanilla-3.png', '/products/on-isolate-vanilla-4.png', '/products/on-isolate-vanilla-5.png'] },
  { id: 'p07', slug: 'on-isolate-chocolate-726g',    name: 'Gold Standard 100% Isolate — Chocolate Bliss 726g',        brand: 'Optimum Nutrition',    category: 'Protein',      subcategory: 'Protein Isolate',      price: 54.99,               weight: '726 g',           rating: 4.8, reviews: 267,                       inStock: true,  image: '/products/on-isolate-choc-main.png', gallery: ['/products/on-isolate-choc-main.png', '/products/on-isolate-choc-2.png', '/products/on-isolate-choc-3.png', '/products/on-isolate-choc-4.png'] },

  // ─── CASEIN ───────────────────────────────────────────────────────────────
  { id: 'p09', slug: 'on-casein-chocolate-1800g',    name: 'Gold Standard 100% Casein — Chocolate Supreme 1.8kg',      brand: 'Optimum Nutrition',    category: 'Protein',      subcategory: 'Casein',               price: 59.99, oldPrice: 69.99, weight: '1.8 kg',       rating: 4.8, reviews: 234, badge: '-14%',        inStock: true,  image: '/products/on-casein-choc-main.png', gallery: ['/products/on-casein-choc-main.png', '/products/on-casein-choc-2.png', '/products/on-casein-choc-3.png', '/products/on-casein-choc-4.png', '/products/on-casein-choc-5.png'] },
  { id: 'p10', slug: 'on-casein-cookies-cream-1746g',name: "Gold Standard 100% Casein — Cookies & Cream 1.74kg",       brand: 'Optimum Nutrition',    category: 'Protein',      subcategory: 'Casein',               price: 57.99,               weight: '1.74 kg',         rating: 4.7, reviews: 178,                       inStock: true,  image: '/products/on-casein-cookies-main.png', gallery: ['/products/on-casein-cookies-main.png', '/products/on-casein-cookies-2.png', '/products/on-casein-cookies-3.png'] },

  // ─── CREATINE ─────────────────────────────────────────────────────────────
  { id: 'c01', slug: 'on-creatine-600g',              name: 'ON Micronized Creatine Powder 600g',                       brand: 'Optimum Nutrition',     category: 'Creatine', subcategory: 'Creatine Monohydrate', price: 29.99,               weight: '600 g',     rating: 4.9, reviews: 421, badge: 'TOP RATED', inStock: true,  image: '/products/on-creatine-main.png', gallery: ['/products/on-creatine-main.png', '/products/on-creatine-2.png', '/products/on-creatine-3.png'] },
  { id: 'c02', slug: 'on-creatine-300g',              name: 'ON Micronized Creatine Powder 300g',                       brand: 'Optimum Nutrition',     category: 'Creatine', subcategory: 'Creatine Monohydrate', price: 17.99,               weight: '300 g',     rating: 4.9, reviews: 311,                     inStock: true,  image: '/products/on-creatine-300g-main.png', gallery: ['/products/on-creatine-300g-main.png'] },
  { id: 'c03', slug: 'balkan-creatine-orange-500g',   name: 'Balkan Creatine BP Orange Powder 500g',                    brand: 'Balkan Pharmaceuticals',category: 'Creatine', subcategory: 'Creatine Monohydrate', price: 19.99, oldPrice: 24.99, weight: '500 g', rating: 4.7, reviews: 188, badge: '-16%',      inStock: true,  image: '/products/balkan-creatine-orange-main.png', gallery: ['/products/balkan-creatine-orange-main.png', '/products/balkan-creatine-orange-2.png'] },
  { id: 'c04', slug: 'now-kre-alkalyn-120caps',       name: 'Now Sports Kre-Alkalyn® Creatine 750mg — 120 Caps',        brand: 'Now Sports',            category: 'Creatine', subcategory: 'Kre-Alkalyn',          price: 22.99,               weight: '120 caps',  rating: 4.7, reviews: 129,                     inStock: true,  image: '/products/now-kre-alkalyn-main.png', gallery: ['/products/now-kre-alkalyn-main.png', '/products/now-kre-alkalyn-2.png', '/products/now-kre-alkalyn-3.png'] },
  { id: 'c06', slug: 'bsn-creatine-dna-309g',         name: 'BSN Creatine DNA — Unflavoured 309g',                      brand: 'BSN',                   category: 'Creatine', subcategory: 'Creatine Monohydrate', price: 22.99, oldPrice: 26.99, weight: '309 g', rating: 4.6, reviews: 112, badge: '-15%',      inStock: true,  image: '/products/bsn-creatine-dna-main.png', gallery: ['/products/bsn-creatine-dna-main.png', '/products/bsn-creatine-dna-2.png', '/products/bsn-creatine-dna-3.png'] },
  { id: 'c07', slug: 'balkan-creatine-unflavored-500g', name: 'Balkan Creatine BP Unflavored Powder 500g',               brand: 'Balkan Pharmaceuticals',category: 'Creatine', subcategory: 'Creatine Monohydrate', price: 19.99,               weight: '500 g',     rating: 4.7, reviews: 156,                     inStock: true,  image: '/products/balkan-creatine-unflavored-main.png', gallery: ['/products/balkan-creatine-unflavored-main.png', '/products/balkan-creatine-unflavored-2.png'] },
  { id: 'c08', slug: 'balkan-creatine-lemon-500g',    name: 'Balkan Creatine BP Lemon Powder 500g',                      brand: 'Balkan Pharmaceuticals',category: 'Creatine', subcategory: 'Creatine Monohydrate', price: 19.99,               weight: '500 g',     rating: 4.6, reviews: 74,                      inStock: true,  image: '/products/balkan-creatine-lemon-main.png', gallery: ['/products/balkan-creatine-lemon-main.png'] },

  // ─── AMINO ACIDS / BCAA ───────────────────────────────────────────────────
  { id: 'a01', slug: 'on-amino-energy-green-apple-585g',  name: 'Essential AMIN.O. Energy — Green Apple 585g',         brand: 'Optimum Nutrition',    category: 'Amino Acids',  subcategory: 'Amino Energy',         price: 37.99, oldPrice: 42.99, weight: '585 g',        rating: 4.8, reviews: 298, badge: '-11%',        inStock: true,  image: '/products/on-amino-energy-apple-main.png', gallery: ['/products/on-amino-energy-apple-main.png', '/products/on-amino-energy-apple-2.png'] },
  { id: 'a02', slug: 'on-amino-energy-fruit-fusion-585g', name: 'Essential AMIN.O. Energy + Electrolytes — Tangerine Wave 285g', brand: 'Optimum Nutrition', category: 'Amino Acids', subcategory: 'Amino Energy', price: 24.99, weight: '285 g', rating: 4.7, reviews: 211, inStock: true, image: '/products/on-amino-energy-tangerine-main.png', gallery: ['/products/on-amino-energy-tangerine-main.png', '/products/on-amino-energy-tangerine-2.png', '/products/on-amino-energy-tangerine-3.png'] },
  { id: 'a03', slug: 'on-amino-energy-electrolytes-285g', name: 'BCAA 1000 — 200 Capsules',                           brand: 'Optimum Nutrition',    category: 'Amino Acids',  subcategory: 'BCAA',                 price: 29.99,               weight: '200 caps',        rating: 4.6, reviews: 134,                       inStock: true,  image: '/products/on-bcaa-1000-200caps-main.png', gallery: ['/products/on-bcaa-1000-200caps-main.png'] },
  { id: 'a04', slug: 'bsn-amino-x-435g',            name: 'Glutamine Powder — Unflavored 300g',                        brand: 'Optimum Nutrition',    category: 'Amino Acids',  subcategory: 'Glutamine',            price: 24.99,               weight: '300 g',           rating: 4.7, reviews: 166,                       inStock: true,  image: '/products/on-glutamine-300g-main.png', gallery: ['/products/on-glutamine-300g-main.png', '/products/on-glutamine-300g-2.png'] },
  { id: 'a05', slug: 'balkan-bcaa-2-1-1-400g',      name: 'BCAA 2:1:1 Powder — 500g',                                 brand: 'Balkan Pharmaceuticals',category: 'Amino Acids', subcategory: 'BCAA',                 price: 21.99,               weight: '500 g',           rating: 4.6, reviews: 98,                        inStock: true,  image: '/products/balkan-bcaa-500g-main.png', gallery: ['/products/balkan-bcaa-500g-main.png', '/products/balkan-bcaa-500g-2.png'] },
  { id: 'a06', slug: 'now-l-glutamine-500g',         name: 'L-Leucine Powder — Unflavored 255g',                       brand: 'Now Sports',           category: 'Amino Acids',  subcategory: 'BCAA',                 price: 17.99,               weight: '255 g',           rating: 4.7, reviews: 143,                       inStock: true,  image: '/products/now-leucine-main.png', gallery: ['/products/now-leucine-main.png', '/products/now-leucine-2.png', '/products/now-leucine-3.png'] },

  // ─── AAS — INJECTIONS ─────────────────────────────────────────────────────
  { id: 'aas01', slug: 'boldenone-equipoise-10ml',              name: 'Boldenone Undecylenate (Equipoise) 250mg/ml — box of 10 amps', brand: 'Alpha Pharma',           category: 'AAS', subcategory: 'Injections', price: 79.99,  weight: '10 × 1ml',  rating: 4.8, reviews: 87,  inStock: true, image: '/products/boldenone-main.png',              gallery: ['/products/boldenone-main.png'],              description: 'Boldenone Undecylenate (Equipoise) — long-acting anabolic derived from testosterone. Promotes steady lean muscle gains with enhanced vascularity and minimal water retention. Sold as a box of 10 × 1ml ampoules (250mg/ml each). Suitable for 12–16 week cycles at 300–600mg/week.' },
  { id: 'aas02', slug: 'nandrolone-decanoate-deca-10ml',        name: 'Nandrolone Decanoate (Deca-Durabolin) 250mg/ml — box of 10 amps', brand: 'Balkan Pharmaceuticals', category: 'AAS', subcategory: 'Injections', price: 74.99,  weight: '10 × 1ml',  rating: 4.8, reviews: 112, inStock: true, image: '/products/deca-durabolin-main.png',         gallery: ['/products/deca-durabolin-main.png'],         description: 'Nandrolone Decanoate (Deca-Durabolin) — one of the most popular mass-building anabolics. Known for significant muscle and strength gains with notable joint support and lubrication. Sold as a box of 10 × 1ml ampoules (250mg/ml). Typical dose 200–400mg/week for 10–14 weeks.' },
  { id: 'aas03', slug: 'nandrolone-phenylpropionate-10ml',      name: 'Nandrolone Phenylpropionate (NPP) 200mg/ml — 5ml vial',        brand: 'Empower Pharmacy',       category: 'AAS', subcategory: 'Injections', price: 69.99,  weight: '5ml vial',  rating: 4.7, reviews: 64,  inStock: true, image: '/products/nandrolone-phenylprop-main.png',  gallery: ['/products/nandrolone-phenylprop-main.png'],  description: 'Nandrolone Phenylpropionate (NPP) — faster-acting version of Deca with a shorter half-life, allowing quicker clearance from the body. Multi-dose 5ml sterile vial. Preferred for shorter cycles; typical dose 100–150mg every other day.' },
  { id: 'aas04', slug: 'sustanon-250-10ml',                     name: 'Sustanon 250 (Testosterone Blend) 250mg/ml — box of 5 amps',  brand: 'BayerPro Schering',      category: 'AAS', subcategory: 'Injections', price: 59.99,  weight: '5 × 1ml',   rating: 4.9, reviews: 143, inStock: true, image: '/products/sustanon-250-main.png',           gallery: ['/products/sustanon-250-main.png'],           description: 'Sustanon 250 — blend of four testosterone esters (Propionate, Phenylpropionate, Isocaproate, Decanoate) providing both rapid onset and long-lasting stable blood levels. Sold as a box of 5 × 1ml ampoules. Typically injected once every 5–7 days at 250–500mg/week.' },
  { id: 'aas05', slug: 'testosterone-propionate-10ml',          name: 'Testosterone Propionate 100mg/ml — box of 5 amps',            brand: 'BayerPro Schering',      category: 'AAS', subcategory: 'Injections', price: 54.99,  weight: '5 × 1ml',   rating: 4.8, reviews: 98,  inStock: true, image: '/products/testosterone-propionate-main.png', gallery: ['/products/testosterone-propionate-main.png'], description: 'Testosterone Propionate — short-acting testosterone ester with rapid onset and fast clearance. Ideal for athletes who need precise control over blood hormone levels. Sold as a box of 5 × 1ml ampoules (100mg/ml). Typically administered every 1–2 days at 50–100mg per injection.' },
  { id: 'aas06', slug: 'testosterone-enanthate-10ml',           name: 'Testosterone Enanthate 250mg/ml — 1 ampoule',                 brand: 'Bayer (Testoviron Depot)', category: 'AAS', subcategory: 'Injections', price: 42.99,  weight: '1ml ampoule', rating: 4.9, reviews: 167, inStock: true, image: '/products/testosterone-enanthate-v2.png',   gallery: ['/products/testosterone-enanthate-v2.png'],   description: 'Testosterone Enanthate (Testoviron Depot) by Bayer — the most widely used long-acting testosterone worldwide. Pharmaceutical grade, intramuscular use only. Sold as individual 1ml ampoules (250mg/ml). Typical dose 250–500mg/week, injected twice weekly.' },
  { id: 'aas07', slug: 'testosterone-undecanoate-nebido-4ml',   name: 'Testosterone Undecanoate (Nebido) 1000mg/4ml — 1 ampoule',    brand: 'Bayer',                  category: 'AAS', subcategory: 'Injections', price: 109.99, weight: '4ml ampoule', rating: 4.7, reviews: 54,  inStock: true, image: '/products/nebido-main.png',                gallery: ['/products/nebido-main.png'],                description: 'Testosterone Undecanoate (Nebido) by Bayer — ultra-long-acting testosterone designed for TRT. A single 4ml ampoule provides stable testosterone levels for 10–14 weeks, requiring only 3–4 injections per year. Pharmaceutical grade, intramuscular use only.' },
  { id: 'aas08', slug: 'trenbolone-acetate-10ml',               name: 'Trenbolone Acetate 100mg/ml — 10ml vial',                     brand: 'Euro-Pharmacies',        category: 'AAS', subcategory: 'Injections', price: 84.99,  weight: '10ml vial', rating: 4.9, reviews: 76,  inStock: true, image: '/products/trenbolone-acetate-main.png',     gallery: ['/products/trenbolone-acetate-main.png'],     description: 'Trenbolone Acetate — one of the most potent anabolic compounds available. Fast-acting short ester ideal for cutting cycles and dramatic body recomposition. 10ml multi-dose vial (100mg/ml). Typically used at 50–100mg every other day. Not recommended for beginners.' },
  { id: 'aas09', slug: 'trenbolone-enanthate-10ml',             name: 'Trenbolone Enanthate 200mg/ml — 10ml vial',                   brand: 'Hilma Biocare',          category: 'AAS', subcategory: 'Injections', price: 87.99,  weight: '10ml vial', rating: 4.9, reviews: 61,  inStock: true, image: '/products/trenbolone-enanthate-main.png',   gallery: ['/products/trenbolone-enanthate-main.png'],   description: 'Trenbolone Enanthate — long-acting version of Trenbolone requiring fewer injections. Delivers exceptional strength, muscle density and fat loss. 10ml multi-dose vial (200mg/ml). Typically injected twice per week at 200–400mg/week. Advanced users only.' },
  { id: 'aas10', slug: 'methenolone-enanthate-primobolan-10ml', name: 'Methenolone Enanthate (Primobolan Depot) 100mg — 1 ampoule',  brand: 'Bayer',                  category: 'AAS', subcategory: 'Injections', price: 48.99,  weight: '1ml ampoule', rating: 4.8, reviews: 49,  inStock: true, image: '/products/primobolan-depot-main.png',       gallery: ['/products/primobolan-depot-main.png'],       description: 'Methenolone Enanthate (Primobolan Depot) by Bayer — premium pharmaceutical-grade injectable. Low androgenic activity with minimal side effects, ideal for lean muscle preservation. Sold as individual 1ml ampoules (100mg/ml). Typical dose 400–600mg/week (4–6 ampoules).' },

  // ─── AAS — TABLETS / CAPSULES ─────────────────────────────────────────────
  { id: 'aas12', slug: 'fluoxymesterone-halotestin-5mg-100tabs',name: 'Fluoxymesterone (Halotestin) 5mg — 100 Tablets',              brand: 'EnhancedRX',             category: 'AAS', subcategory: 'Tablets', price: 54.99,  weight: '100 tabs', rating: 4.7, reviews: 41,  inStock: true, image: '/products/halotestin-main.png', gallery: ['/products/halotestin-main.png'] },
  { id: 'aas14', slug: 'dht-andractim-25mg-60tabs',             name: 'Proviron (Mesterolone) 25mg — 20 Tablets',                    brand: 'Bayer',                  category: 'AAS', subcategory: 'Tablets', price: 49.99,  weight: '20 tabs',  rating: 4.6, reviews: 27,  inStock: true, image: '/products/proviron-main.png', gallery: ['/products/proviron-main.png'] },
  { id: 'aas16', slug: 'methandienone-dianabol-10mg-100tabs',   name: 'Methandienone (Dianabol) 10mg — 100 Tablets',                 brand: 'Evolve Biolabs',         category: 'AAS', subcategory: 'Tablets', price: 34.99,  weight: '100 tabs', rating: 4.9, reviews: 198, inStock: true, image: '/products/dianabol-main.png', gallery: ['/products/dianabol-main.png'] },
  { id: 'aas17', slug: 'oxandrolone-anavar-10mg-100tabs',       name: 'Oxandrolone (Anavar) 10mg — 100 Tablets',                     brand: 'Bayer Schering',         category: 'AAS', subcategory: 'Tablets', price: 69.99,  weight: '100 tabs', rating: 4.9, reviews: 154, inStock: true, image: '/products/anavar-main.png', gallery: ['/products/anavar-main.png'] },
  { id: 'aas18', slug: 'stanozolol-winstrol-10mg-100tabs',      name: 'Stanozolol (Winstrol) 50mg — 60 Tablets',                     brand: 'Cambridge Research',     category: 'AAS', subcategory: 'Tablets', price: 39.99,  weight: '60 tabs',  rating: 4.8, reviews: 132, inStock: true, image: '/products/winstrol-main.png', gallery: ['/products/winstrol-main.png'] },
  { id: 'aas19', slug: 'turinabol-tbol-10mg-100tabs',           name: 'Turinabol (Oral Tbol) 10mg — 100 Tablets',                    brand: 'Trusted Nutrients Pharma', category: 'AAS', subcategory: 'Tablets', price: 44.99, weight: '100 tabs', rating: 4.8, reviews: 117, inStock: true, image: '/products/turinabol-main.png', gallery: ['/products/turinabol-main.png'] },
  { id: 'aas21', slug: 'oxymetholone-anadrol-50mg-100tabs',     name: 'Oxymetholone (Anadrol) 50mg — 100 Tablets',                   brand: 'Bayer Schering',         category: 'AAS', subcategory: 'Tablets', price: 59.99,  weight: '100 tabs', rating: 4.8, reviews: 89,  inStock: true, image: '/products/oxymetholone-main.png', gallery: ['/products/oxymetholone-main.png'] },
  { id: 'aas20', slug: '4-chloro-methyl-androst-chlorodehydro',  name: 'Turinabol 5mg — 50 Tablets',                                  brand: 'Bayer Pharma AG',        category: 'AAS', subcategory: 'Tablets', price: 49.99, weight: '50 tabs',  rating: 4.7, reviews: 38,  inStock: true, image: '/products/turinabol-bayer-main.png', gallery: ['/products/turinabol-bayer-main.png'] },

  // ─── Peptides — Growth Hormone Stimulants (Secretagogues) ───
  { id: 'pep01', slug: 'ghrp-6-hexarelin-5mg',           name: 'GHRP-6 (Hexarelin) 5mg — 1 vial',                brand: 'Peptide Sciences',     category: 'Peptides', subcategory: 'secretagogues', price: 55.00,  weight: '5mg / vial',      rating: 4.7, reviews: 62,  inStock: true, image: '/products/ghrp6-hexarelin-main.png', gallery: ['/products/ghrp6-hexarelin-main.png'], description: 'GHRP-6 (Growth Hormone Releasing Peptide-6) is a potent GH secretagogue that stimulates pituitary GH release. Increases appetite and promotes lean muscle growth. Typical dose: 100–300 mcg per injection, 2–3× daily.' },
  { id: 'pep02', slug: 'ghrp-2-pralmorelin-5mg',         name: 'GHRP-2 (Pralmorelin) 5mg — 1 vial',              brand: 'Peptide Sciences',     category: 'Peptides', subcategory: 'secretagogues', price: 55.00,  weight: '5mg / vial',      rating: 4.7, reviews: 48,  inStock: true, image: '/products/ghrp2-main.png', gallery: ['/products/ghrp2-main.png'], description: 'GHRP-2 is a synthetic hexapeptide that triggers strong GH pulses from the pituitary. Minimal effect on appetite compared to GHRP-6. Supports muscle gain, fat loss, and recovery. Dose: 100–300 mcg per injection.' },
  { id: 'pep03', slug: 'ipamorelin-5mg',                  name: 'Ipamorelin 5mg — 1 vial',                        brand: 'Peptide Sciences',     category: 'Peptides', subcategory: 'secretagogues', price: 57.00,  weight: '5mg / vial',      rating: 4.8, reviews: 91,  inStock: true, image: '/products/ipamorelin-main.png', gallery: ['/products/ipamorelin-main.png'], description: 'Ipamorelin is a selective GH secretagogue with no significant cortisol or prolactin elevation. Ideal for steady GH pulses, lean muscle preservation, and anti-aging protocols. Dose: 200–300 mcg, 2–3× daily.' },
  { id: 'pep04', slug: 'cjc-1295-2mg',                   name: 'CJC-1295 (DAC) 2mg — 1 vial',                    brand: 'Peptide Sciences',     category: 'Peptides', subcategory: 'secretagogues', price: 63.00,  weight: '2mg / vial',      rating: 4.8, reviews: 74,  inStock: true, image: '/products/cjc-1295-main.png', gallery: ['/products/cjc-1295-main.png'], description: 'CJC-1295 with DAC is a long-acting GHRH analogue that extends GH release for up to 8 days after a single injection. Commonly stacked with Ipamorelin for synergistic GH elevation. Dose: 1–2 mg per week.' },
  { id: 'pep05', slug: 'ibutamoren-mk677-25mg-60caps',   name: 'Ibutamoren (MK-677) 25mg — 60 Capsules',         brand: 'Swiss Pharmaceuticals', category: 'Peptides', subcategory: 'secretagogues', price: 99.99,  weight: '60 caps',         rating: 4.9, reviews: 187, inStock: true, image: '/products/ibutamoren-mk677-main.png', gallery: ['/products/ibutamoren-mk677-main.png'], description: 'Ibutamoren (MK-677) is the most popular oral GH secretagogue. Increases IGF-1 and GH levels, promotes deep sleep, muscle fullness, and recovery. Non-peptide compound taken orally. Dose: 25 mg once daily, preferably at night.' },
  { id: 'pep06', slug: 'sermorelin-grf-2mg',             name: 'Sermorelin (GRF 1-29) 2mg — 1 vial',             brand: 'Peptide Sciences',     category: 'Peptides', subcategory: 'secretagogues', price: 59.00,  weight: '2mg / vial',      rating: 4.6, reviews: 43,  inStock: true, image: '/products/sermorelin-main.png', gallery: ['/products/sermorelin-main.png'], description: 'Sermorelin (Mod GRF 1-29) is a GHRH analogue that stimulates the pituitary to produce GH naturally. Used in anti-aging and wellness protocols. Dose: 200–300 mcg subcutaneously before bed.' },

  // ─── Peptides — Hormones & Growth Factors ───
  { id: 'pep07', slug: 'somatotropin-hgh-10iu',          name: 'Somatropin (HGH) 100 IU Kit — 10 × 10 IU vials', brand: 'Hilma Biocare',        category: 'Peptides', subcategory: 'hormones', price: 209.99, weight: '10 × 10 IU vials', rating: 4.9, reviews: 214, inStock: true, image: '/products/somatropin-hgh-main.png', gallery: ['/products/somatropin-hgh-main.png'], description: 'Somatropin by Hilma Biocare. Kit of 10 × 10 IU lyophilized vials (100 IU total) — ~€18.50 per vial. Recombinant human Growth Hormone that promotes muscle hypertrophy, lipolysis, and tissue regeneration. Used in TRT and performance protocols. Dose: 2–4 IU/day subcutaneously. Refrigerate at 2–8°C.' },
  { id: 'pep08', slug: 'igf-1-lr3-100mcg',               name: 'IGF-1 LR3 (Receptor Grade) 100 mcg — 1 vial',    brand: 'Peptide Sciences',     category: 'Peptides', subcategory: 'hormones', price: 55.00,  weight: '100 mcg / vial',  rating: 4.7, reviews: 88,  inStock: true, image: '/products/igf1-lr3-main.png', gallery: ['/products/igf1-lr3-main.png'], description: 'IGF-1 LR3 (Long R3 Insulin-like Growth Factor-1) is a potent anabolic peptide that promotes muscle cell hyperplasia and nutrient uptake. Half-life ~20–30 h. Dose: 20–100 mcg/day post-workout, subcutaneously or intramuscularly.' },
  { id: 'pep09', slug: 'mgf-mechano-growth-factor-2mg',  name: 'MGF IGF-1 Ec (Mechano Growth Factor) 5 mg — 1 vial', brand: 'Peptide Sciences', category: 'Peptides', subcategory: 'hormones', price: 84.99,  weight: '5mg / vial',      rating: 4.6, reviews: 41,  inStock: true, image: '/products/mgf-igf1-main.png', gallery: ['/products/mgf-igf1-main.png'], description: 'Mechano Growth Factor is a splice variant of IGF-1 released locally in muscle tissue following exercise. Activates satellite cells for muscle repair and growth. Dose: 100–200 mcg injected into the target muscle within 30 min post-workout.' },
  { id: 'pep10', slug: 'insulin-novorapid-100iu-3ml',    name: 'NovoRapid® FlexPen 100 U/ml — box of 5 × 3 ml',  brand: 'Novo Nordisk',         category: 'Peptides', subcategory: 'hormones', price: 89.99,  weight: '5 × 3 ml pens',   rating: 4.8, reviews: 127, inStock: true, image: '/products/insulin-novorapid-main.png', gallery: ['/products/insulin-novorapid-main.png'], description: 'NovoRapid® FlexPen by Novo Nordisk. Box of 5 pre-filled disposable pens × 3 ml (100 U/ml each, 300 U per pen / 1500 U total). ~€13 per pen. Fast-acting insulin analogue (aspart) used peri-workout to drive glucose and amino acids into muscle cells. Onset ~10–20 min, duration ~3–5 h. Requires strict blood glucose monitoring. For experienced users only. Store at 2–8°C.' },
  { id: 'pep11', slug: 'hcg-pregnyl-5000iu',             name: 'HCG Pregnyl® 5000 IU — 1 amp + solvent',         brand: 'MSD (Organon)',        category: 'Peptides', subcategory: 'hormones', price: 49.99,  weight: '5000 IU / 1 amp', rating: 4.8, reviews: 156, inStock: true, image: '/products/hcg-pregnyl-main.png', gallery: ['/products/hcg-pregnyl-main.png'], description: 'Pregnyl® 5000 IU by MSD (Organon). Each box contains 1 ampoule of lyophilized hCG powder (5000 IU) + 1 ampoule of solvent for injection. Market price: ~€25/amp. Human Chorionic Gonadotropin mimics LH and stimulates testicular testosterone production. Used during and after AAS cycles to prevent testicular atrophy and restore HPTA function. Dose: 500–1000 IU every 3–4 days, IM or subcutaneously. Store at 2–15°C.' },
  { id: 'pep12', slug: 'epo-erythropoietin-2000iu',      name: 'Eprex® (Epoetin alfa) 2000 IU — box of 6 syringes', brand: 'Cilag / Janssen',   category: 'Peptides', subcategory: 'hormones', price: 124.99, weight: '6 × 0.5 ml',      rating: 4.5, reviews: 34,  inStock: true, image: '/products/eprex-epo-main.png', gallery: ['/products/eprex-epo-main.png'], description: 'Eprex® (Epoetin alfa) 2000 IU/0.5 ml by Cilag/Janssen. Box of 6 pre-filled syringes. Market price: ~€100/box. Recombinant human erythropoietin that stimulates red blood cell production, increasing oxygen-carrying capacity and endurance. Primarily used in endurance sports. Dose: 50–200 IU/kg subcutaneously 3× per week. Store at 2–8°C.' },
  { id: 'pep13', slug: 'follistatin-344-1mg',             name: 'Follistatin 344 1 mg — 1 vial',                  brand: 'Peptide Sciences',     category: 'Peptides', subcategory: 'hormones', price: 169.99, weight: '1mg / vial',      rating: 4.6, reviews: 29,  inStock: true, image: '/products/follistatin-344-main.png', gallery: ['/products/follistatin-344-main.png'], description: 'Follistatin-344 is a naturally occurring protein that inhibits myostatin, effectively removing a key brake on muscle growth. Promotes rapid muscle hypertrophy. Dose: 50–100 mcg/day intramuscularly for 10-day cycles.' },

  // ─── Hormone & Metabolic Modulators — SARMs ───
  { id: 'mod01', slug: 'ostarine-mk2866-10mg-60caps',    name: 'Ostarine (MK-2866) 10mg — 60 Capsules',          brand: 'Hardcore Supplements', category: 'Modulators', subcategory: 'sarms', price: 39.99, weight: '60 caps', rating: 4.8, reviews: 203, inStock: true, image: '/products/ostarine-mk2866-main.png', gallery: ['/products/ostarine-mk2866-main.png'], description: 'Ostarine (MK-2866, Enobosarm) — the most researched SARM. Promotes lean muscle retention and bone density with minimal androgenic side effects. Suitable for cutting and recomposition. Dose: 10–25 mg/day for 8–12 weeks.' },
  { id: 'mod02', slug: 'ligandrol-lgd4033-5mg-60caps',   name: 'Ligandrol (LGD-4033) 5mg — 60 Capsules',         brand: 'RP Pharma',            category: 'Modulators', subcategory: 'sarms', price: 54.99, weight: '60 caps', rating: 4.8, reviews: 176, inStock: true, image: '/products/ligandrol-lgd4033-main.png', gallery: ['/products/ligandrol-lgd4033-main.png'], description: 'Ligandrol (LGD-4033) is one of the most potent SARMs for lean mass gains. Significantly increases strength and muscle size with minimal water retention. Dose: 5–10 mg/day for 8 weeks. Requires PCT.' },
  { id: 'mod03', slug: 'rad140-testolone-10mg-60caps',   name: 'RAD-140 (Testolone) 10mg — 60 Capsules',         brand: 'Hardcore Supplements', category: 'Modulators', subcategory: 'sarms', price: 69.99, weight: '60 caps', rating: 4.9, reviews: 154, inStock: true, image: '/products/rad140-testolone-main.png', gallery: ['/products/rad140-testolone-main.png'], description: 'RAD-140 (Testolone) is among the most anabolic SARMs, with a high anabolic-to-androgenic ratio. Promotes rapid strength and lean muscle gains. Dose: 10–20 mg/day for 8 weeks. PCT recommended.' },
  { id: 'mod04', slug: 'andarine-s4-25mg-60caps',        name: 'Andarine (S-4) 25mg — 60 Capsules',              brand: 'Swiss Pharmaceuticals', category: 'Modulators', subcategory: 'sarms', price: 44.99, weight: '60 caps', rating: 4.6, reviews: 98,  inStock: true, image: '/products/andarine-s4-main.png', gallery: ['/products/andarine-s4-main.png'], description: 'Andarine (S-4) is a SARM known for promoting hardness, vascularity, and fat loss while preserving muscle tissue. Effective in caloric deficit. Dose: 25–50 mg/day. May cause temporary vision tint at high doses.' },
  { id: 'mod05', slug: 's23-mastorin-10mg-60caps',       name: 'S-23 (Mastorin) 10mg — 60 Capsules',             brand: 'Epic Labs',            category: 'Modulators', subcategory: 'sarms', price: 64.99, weight: '60 caps', rating: 4.7, reviews: 67,  inStock: true, image: '/products/s23-mastorin-main.png', gallery: ['/products/s23-mastorin-main.png'], description: 'S-23 is a potent full agonist SARM with strong anabolic effects comparable to low-dose steroids. Promotes dense muscle gains and fat oxidation. Dose: 10–20 mg/day. Requires PCT due to suppression.' },

  // ─── Hormone & Metabolic Modulators — Aromatase Inhibitors ───
  { id: 'mod06', slug: 'anastrozole-arimidex-1mg-30tabs', name: 'Anastrozole (Arimidex) 1mg — 28 Tablets',       brand: 'AstraZeneca',          category: 'Modulators', subcategory: 'aromatase-inhibitors', price: 39.99, weight: '28 tabs', rating: 4.8, reviews: 189, inStock: true, image: '/products/anastrozole-arimidex-main.png', gallery: ['/products/anastrozole-arimidex-main.png'], description: 'Anastrozole (Arimidex) is a potent non-steroidal aromatase inhibitor. Used on-cycle to prevent estrogen-related side effects (gynecomastia, water retention). Dose: 0.5–1 mg every other day during AAS cycles.' },
  { id: 'mod07', slug: 'letrozole-femara-2-5mg-30tabs',  name: 'Letrozole (Femara) 2.5mg — 30 Tablets',          brand: 'Novartis',             category: 'Modulators', subcategory: 'aromatase-inhibitors', price: 41.99, weight: '30 tabs', rating: 4.7, reviews: 112, inStock: true, image: '/products/letrozole-femara-main.png', gallery: ['/products/letrozole-femara-main.png'], description: 'Letrozole (Femara) is the most potent oral aromatase inhibitor, capable of reducing estrogen by up to 98%. Used during heavy aromatizing cycles or to treat gynecomastia. Dose: 0.5–2.5 mg/day. Use with caution.' },
  { id: 'mod08', slug: 'exemestane-aromasin-25mg-30tabs', name: 'Exemestane (Aromasin) 25mg — 30 Tablets',       brand: 'Pfizer',               category: 'Modulators', subcategory: 'aromatase-inhibitors', price: 44.99, weight: '30 tabs', rating: 4.7, reviews: 134, inStock: true, image: '/products/exemestane-aromasin-main.png', gallery: ['/products/exemestane-aromasin-main.png'], description: 'Exemestane (Aromasin) is a steroidal aromatase inactivator (suicidal AI). Permanently binds and deactivates aromatase. Preferred by many for PCT due to mild androgenic activity. Dose: 12.5–25 mg every other day.' },

  // ─── Hormone & Metabolic Modulators — SERMs / PCT ───
  { id: 'mod09', slug: 'tamoxifen-nolvadex-20mg-30tabs', name: 'Tamoxifen Citrate (Nolvadex-D) 20mg — 30 Tablets', brand: 'AstraZeneca',        category: 'Modulators', subcategory: 'serms', price: 24.99, weight: '30 tabs', rating: 4.8, reviews: 241, inStock: true, image: '/products/tamoxifen-nolvadex-main.png', gallery: ['/products/tamoxifen-nolvadex-main.png'], description: 'Tamoxifen Citrate (Nolvadex) is a selective estrogen receptor modulator (SERM). Essential for post-cycle therapy (PCT) to restore natural testosterone production. Blocks estrogen receptors in breast tissue. Dose: 20–40 mg/day for 4–6 weeks post-cycle.' },
  { id: 'mod10', slug: 'clomiphene-clomid-50mg-30tabs',  name: 'Clomiphene Citrate (Clomid) 50mg — 30 Tablets',  brand: 'Sanofi',               category: 'Modulators', subcategory: 'serms', price: 29.99, weight: '30 tabs', rating: 4.7, reviews: 198, inStock: true, image: '/products/clomid-main.png', gallery: ['/products/clomid-main.png'], description: 'Clomiphene Citrate (Clomid) is a SERM widely used in PCT to stimulate LH and FSH release from the pituitary, restoring endogenous testosterone. Often combined with Nolvadex. Dose: 50 mg/day for 4 weeks post-cycle.' },

  // ─── Hormone & Metabolic Modulators — Metabolic ───
  { id: 'mod11', slug: 'meldonium-mildronate-500mg-60caps', name: 'Meldonium (Mildronat®) 500mg — 60 Capsules', brand: 'Grindeks',             category: 'Modulators', subcategory: 'metabolic', price: 39.99, weight: '60 caps', rating: 4.6, reviews: 87,  inStock: true, image: '/products/meldonium-mildronate-main.png', gallery: ['/products/meldonium-mildronate-main.png'], description: 'Meldonium (Mildronate) is a metabolic modulator that inhibits carnitine biosynthesis, reducing fatty acid oxidation and boosting glucose utilization under hypoxia. Improves endurance, recovery, and cardiac efficiency. Dose: 500–1000 mg/day in cycles.' },
  { id: 'mod12', slug: 'cardarine-gw501516-10mg-60caps',  name: 'Cardarine (GW-501516) 10mg — 60 Capsules',      brand: 'Biowell Labs',         category: 'Modulators', subcategory: 'metabolic', price: 41.99, weight: '60 caps', rating: 4.7, reviews: 143, inStock: true, image: '/products/cardarine-gw501516-main.png', gallery: ['/products/cardarine-gw501516-main.png'], description: 'Cardarine (GW-501516) is a PPARδ agonist that dramatically improves endurance and fat oxidation. Often called "exercise in a pill". Promotes fatty acid burning without muscle catabolism. Dose: 10–20 mg/day for up to 8 weeks.' },
  { id: 'mod13', slug: 'sr9009-stenabolic-10mg-60caps',   name: 'SR-9009 (Stenabolic) 10mg — 60 Capsules',       brand: 'Biowell Labs',         category: 'Modulators', subcategory: 'metabolic', price: 44.99, weight: '60 caps', rating: 4.6, reviews: 91,  inStock: true, image: '/products/sr9009-stenabolic-main.png', gallery: ['/products/sr9009-stenabolic-main.png'], description: 'SR-9009 (Stenabolic) is a Rev-Erbα agonist that regulates circadian rhythm, metabolism, and mitochondrial biogenesis. Enhances endurance, reduces fat storage, and improves recovery. Dose: 20–30 mg/day in divided doses.' },



];

export const CATEGORIES_NAV = [
  { key: 'all',          label: 'All Products' },
  { key: 'womens-health', label: "Women's Health" },
  { key: 'protein',      label: 'Protein' },
  { key: 'creatine',     label: 'Creatine' },
  { key: 'amino-acids',  label: 'Amino Acids' },
  { key: 'aas',          label: 'Anabolic Androgenic Steroids' },
  { key: 'peptides',     label: 'Peptides & Growth Hormones' },
  { key: 'modulators',   label: 'Hormone & Metabolic Modulators' },
];

export const BRANDS_NAV = [
  'Optimum Nutrition',
  'BSN',
  'Now Sports',
  'Balkan Pharmaceuticals',
];
